#+AUTHOR: Jackson Fretheim
#+HUGO_SECTION: posts
#+HUGO_BASE_DIR: ../
#+HUGO_WEIGHT: auto
#+HUGO_AUTO_SET_LASTMOD: t

* False Framing: A Threat to True Historical Understanding :bible:history:
:PROPERTIES:
:EXPORT_FILE_NAME: false-framing
:EXPORT_DATE: 2022-05-04
:END:

The other day, while browsing a forum, I came across someone who was troubled by objections to the traditional authorship of certain books in the scriptural canon. This issue is an interesting one because it calls to mind the importance of framing. False framing of evidence, even real evidence, can lead you to the wrong conclusions. Thus, in the pursuit of truth it is as important to correctly /frame evidence/ as it is to /have the evidence/ in the first place.

Most dangerous in false framing is how it can abuse the truth. Valid questions, as well as accurate data and criticism, can be leveraged by someone to "prove" their personal opinion beyond what the evidence requires. This is often done to the exclusion of other valid views and conclusions that the available evidence could lead you to reasonably believe. When someone presents me with new evidence, along with a new frame of reference, I always try to take a step back and look at what it /actually/ proves or disproves. Having a deep knowledge of a subject matter can help, and when you identify a gap in your knowledge it should be used as an opportunity to learn. Don't allow the difficulty of learning let you fall back on the trap of using framing devices as a shortcut.

Back on the topic of Biblical authorship, it should be understood that certain evidence, or rather certain _kinds_ of evidence, cannot _disprove_ the traditional authorship (though they /may/ allow alternate /theories/). Two works, supposed to have been written by the same author, which use different writing styles can't /disprove/ that the same author wrote both. They could simply be trying different styles to better suit their audience, or developing their literary style in response to feedback. Different styles can only introduce a /possibility/ that there are separate authors under another /potential/ theory. Don't allow evidence of literary variety distract you from the other established arguments and evidence.
